spring:
  datasource:
     url: jdbc:mysql://localhost:3306/article_management_system?serverTimezone=GMT%2B8 & characterEnconding=utf-8&useSSL=false
     username: root
     password: admin
     driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf:
#    cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#mybatis:
#  typeAliasesPackage: com.hubu713.mapper
#  mapperLocations: classpath:mapper/*.xml


